### ISSUE TITLE
sumoselect.css change the body font-family and color

### ISSUE THREAD

**Issue by liorg2** [HemantNegi/jquery.sumoselect#27]
is it possible to remove this rule from the css file?

body, p, div, select { padding: 0; margin: 0; outline: none; color: #000; font-family: calibri; }

thank!

**Comment by HemantNegi** [comment]
yup sure you can customize css according to your convenience,
but i cant remove it from the source.

cheers!!

**Comment by ypanshin** [comment]
Hi, 
The global style of color and font overwrite my style on page. 
Could it be changed to something like this:
```css
.SlectBox, .SlectBox p, .SlectBox div, .SlectBox select{padding: 0; margin: 0; outline: none; color: #000; font-family: calibri;}
```
