### ISSUE TITLE
Display more than 8 options in list.

### ISSUE THREAD

**Issue by jonburdon** [HemantNegi/jquery.sumoselect#296]
I have a long list of options. The default display is 8 - I can't seem to display more than that. Am using very basic setup with example code. Have read docs and tried csvDispCount option.

`$('.filter-dropdown').SumoSelect({ search: true, searchText: 'Search industry or scroll down.'});
`

**Comment by Zenoo** [comment]
The `max-height` property on the dropdown is set to `250px`.
https://github.com/HemantNegi/jquery.sumoselect/blob/f5070d8d4f25ffb0addbccfcf1bdbec4c277f3a0/sumoselect.css#L37-L40

All you need to do is either unset the property or adjust it to your liking: 

```css
.SumoSelect > .optWrapper > .options{
  max-height: unset;
}
```
OR

```css
.SumoSelect > .optWrapper > .options{
  max-height: 350px;
}
```
